name: Build
on: push
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: testdb        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
    - name: Check out code
      uses: actions/checkout@v2
    - name: Download Go dependencies
      run: go mod download
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      continue-on-error: true
      with:
        version: v1.48.0
        skip-pkg-cache: true
        skip-build-cache: true
        args: --timeout=5m
    - name: Run tests
      run: go test -race -v -test-pg ./...