name: Build
on: push
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
    # Instructions from https://www.postgresql.org/download/linux/ubuntu/
    - name: Install PostgreSQL
      run: |
        echo 'deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main' | sudo tee /etc/apt/sources.list.d/pgdg.list
        sudo curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib
    - name: Check out code
      uses: actions/checkout@v2
    - name: Download Go dependencies
      run: go mod download
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      continue-on-error: true
      with:
        version: v1.48.0
        skip-pkg-cache: true
        skip-build-cache: true
        args: --timeout=5m
    - name: Run tests
      run: go test -race -v ./...